### ISSUE TITLE
Take photo sometimes does nothing

### ISSUE THREAD

**Issue by simon-pau** [proninyaroslav/blink-comparison#20]
Hello,

when I want to compare a photo and take the new photo, the take-photo button sometimes does nothing.
I need to force-close the app and restart it to work again.
I installed it from f-droid and use Android 14.

**Comment by simon-pau** [comment]
To clarify: The camera takes a photo (sound is playing), it does not go to the compare screen.

**Comment by proninyaroslav** [comment]
Fixed. Camera library updated to latest version. Wait for release, if it happens again feel free to open issue
