### ISSUE TITLE
Autofocus does a really bad job for close-up shots

### ISSUE THREAD

**Issue by UndeadDevel** [proninyaroslav/blink-comparison#21]
The app's autofocus barely works when trying to take close-up photographs, e.g. of screws with glitter; it will often "search" continuously for the correct setting, but just cycle past where the image is sharp and start all over again.

It would be nice if either autofocus was improved or a manual focus (e.g. slider) introduced (or both).

What I'm talking about:

![autofocus_issue_blink_comparison_app](https://github.com/proninyaroslav/blink-comparison/assets/30495439/4bb5e89d-e586-452c-b628-795058557a4f)

**Comment by proninyaroslav** [comment]
There will be an update soon and maybe the problem will be solved. You can also tap on the viewfinder to manually set the focus. I think I will add disabling autofocus as an option.
