### ISSUE TITLE
Кнопка прозрачность пропадает

### ISSUE THREAD

**Issue by OmlineEditor** [proninyaroslav/blink-comparison#5]
Когда делаешь второе фото появляется кнопка выставить прозрачность, но эта кнопка появляется на 2 секунды и потом пропадает и вытащить ее нельзя, есть подозрение что это частично связанно с https://github.com/proninyaroslav/blink-comparison/issues/4
Пофиксите баг и сделайте чтобы кнопка была всегда

**Comment by proninyaroslav** [comment]
Это не баг. Верхний бар возвращается свайпом, аналогичное поведение и для кнопок навигации.
