### ISSUE TITLE
Лишние ресиверы

### ISSUE THREAD

**Issue by OmlineEditor** [proninyaroslav/blink-comparison#7]
в программе есть лишние ресиверы, они отвечают за загрузку программы при включении телефона и при обновлении приложения и перезагрузке телефона кажется. Они по большому счету не нужны вообще и без них все отлично работает (я проверила) и еще меньше программ в память при загрузке лезут. Можно эти ресиверы удалить?

![res](https://user-images.githubusercontent.com/13348933/151384851-fb46e484-6513-4b2d-aec4-2773d4917e96.jpg)

**Comment by proninyaroslav** [comment]
Это ресиверы из библиотеки показа уведомлений (конкретно для запланированных уведомлений которые в приложении не используются). Отключил их программно: https://github.com/proninyaroslav/blink-comparison/commit/54ee62fafdf874ead8d4d6ff8e76d55244c605b9
